### ISSUE TITLE
Arrange items when creating (feature request)

### ISSUE THREAD

**Issue by sevdimali** [adilek/jirtdan#68]
Hi, When we try to create multiple items.
All of them are positioned by the same coordinate like below image:

![jirtdan_na](https://user-images.githubusercontent.com/7975087/116687370-1a03af80-a9c6-11eb-96bb-7063bf587a63.png)

I think it will be more user-friendly to arrange them, under each other or side by side.

![jirtdan_a](https://user-images.githubusercontent.com/7975087/116687374-1bcd7300-a9c6-11eb-9b86-aea5e0635ddb.png)

**Comment by adilek** [comment]
Hi Sevdimali,
Currently I do not have a chance to work on this project actively. Honestly, it was just an experiment I worked on and some of friends contributed later. 

You can work on this feature yourself and submit a PR. Ping me anytime if you need assistance.

Thanks.

**Comment by sevdimali** [comment]
thanks for quick reply. Yes understood :)
