### ISSUE TITLE
Serving application as webpage in real-time

### ISSUE THREAD

**Issue by ziyaddin** [adilek/jirtdan#7]
Actually, we can serve the application in real-time by copying application files to new `gh-pages` branch. Then we can access the application as a webpage. It will be easier for developers to preview the current state of the project.

**Comment by adilek** [comment]
Thank you for the idea. I will update the switch button, high/low constant components and do as you suggest.

**Comment by adilek** [comment]
You can access the online demo on http://jirtdan.org/
