### ISSUE TITLE
Errors on Load: XMLHTTPRequest and ProgressEvent

### ISSUE THREAD

**Issue by ziyaddin** [adilek/jirtdan#8]
Application gives the following errors when app webpage is loaded:

![image](https://cloud.githubusercontent.com/assets/1016523/24555682/16dbe63a-1643-11e7-91d5-629ea0741aa9.png)

Steps to reproduce the error:
- open `app.html` file in Chrome.

**Comment by ziyaddin** [comment]
It seems `XMLHTTPRequest` error is related with filesystem:
http://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local

**Comment by adilek** [comment]
Hi Ziyaddin,
The error message explains about a cross-origin issue. Usually, you can see this kind of error when you use AJAX request to the different host. Browsers do not allow cross-origin AJAX requests.

In our case, you are trying to open a local HTML file, and browser tries to send AJAX request as well. Therefore you get the error.

All you need is to use local web server.

It was my mistake that did not provide instructions.

I updated the README file and made little explanation. (https://github.com/adilek/jirtdan/commit/b0c5b2c18f8d7078f61fadc71209db6dde9508a8)
Installation instructions will be changed in future. As current instruction is temporary I keep it simple.
